package com.just.print.db.bean;

import com.just.print.db.dao.DaoSession;

import de.greenrobot.dao.DaoException;

import com.just.print.db.dao.MarkDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table MARK.
 */
public class Mark {

    private String name;
    private Integer state;
    private Long version;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient MarkDao myDao;


    // KEEP FIELDS - put your custom fields here
    public boolean select;
    // KEEP FIELDS END

    public Mark() {
    }

    public Mark(String name) {
        this.name = name;
    }

    public Mark(String name, Integer state, Long version) {
        this.name = name;
        this.state = state;
        this.version = version;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMarkDao() : null;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object o) {

        return toString().equals(o.toString());
    }

    public void updateAndUpgrade() {
        version = com.just.print.db.expand.DaoExpand.queryMaxVersion(myDao);
        update();
    }

    public void logicDelete() {
        state = com.just.print.db.expand.State.delete;
        updateAndUpgrade();
    }

    @Override
    public int hashCode() {
        return toString().hashCode();
    }

    @Override
    public String toString() {

        return String.valueOf(name);
    }
    // KEEP METHODS END

}
